import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { Manrope } from "next/font/google";
import { connectToDB } from "@/database";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDB();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${manrope.className} antialiased`}>
          <Toaster richColors />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
